package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"math/rand"
	"my-graphql-server/graph/model"
	"strconv"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	// panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
	todo := &model.Todo{
		ID:   strconv.Itoa(rand.Int()),
		Text: input.Text,
		Done: false,
		User: &model.User{
			ID:   input.UserID,
			Name: "Temp-User",
		},
	}
	r.TodoList = append(r.TodoList, todo)
	return todo, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.QueryInput) (*model.UserEducation, error) {
	// panic(fmt.Errorf("not implemented: CreateUser - createUser"))
	user := &model.UserEducation{
		ID:         strconv.Itoa(rand.Int()),
		School:     input.School,
		Graduation: input.Graduation,
	}
	r.UserList = append(r.UserList, user)
	return user, nil
}

// CreateCar is the resolver for the createCar field.
func (r *mutationResolver) CreateCar(ctx context.Context, input model.QueryCarDetails) (*model.Cars, error) {
	// panic(fmt.Errorf("not implemented: CreateCar - createCar"))
	car := &model.Cars{
		Brand:   input.Brand,
		Model:   input.Model,
		Price:   input.Price,
		MfdYear: input.MfdYear,
	}
	r.CarsList = append(r.CarsList, car)
	return car, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	// panic(fmt.Errorf("not implemented: Todos - todos"))
	fmt.Print("Hi")
	return r.TodoList, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) ([]*model.UserEducation, error) {
	// panic(fmt.Errorf("not implemented: User - user"))
	return r.UserList, nil
}

// Cars is the resolver for the cars field.
func (r *queryResolver) Cars(ctx context.Context) ([]*model.Cars, error) {
	// panic(fmt.Errorf("not implemented: Cars - cars"))
	return r.CarsList, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
