// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cars struct {
	Brand   string `json:"brand"`
	Model   string `json:"model"`
	Price   string `json:"price"`
	MfdYear string `json:"mfdYear"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type QueryCarDetails struct {
	Brand   string `json:"brand"`
	Model   string `json:"model"`
	Price   string `json:"price"`
	MfdYear string `json:"mfdYear"`
}

type QueryInput struct {
	Name       string `json:"name"`
	School     string `json:"school"`
	Graduation string `json:"graduation"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserEducation struct {
	ID         string `json:"id"`
	School     string `json:"school"`
	Graduation string `json:"Graduation"`
}
